#!/bin/bash
# This shell script was created at solowizard.com
#
# Usage:
#   Running the script remotely:
#     bash < <(curl -s http://www.solowizard.com/soloist_scripts/7em2g6.sh )
#   Running the script if you have downloaded it:
#     ./7em2g6.sh
#
# http://github.com/tommyh/solo_wizard
# (c) 2012, Tom Hallett
# This script may be freely distributed under the MIT license.

pushd `pwd`
if rvm --version 2>/dev/null; then
  gem install soloist
else
  sudo gem install soloist
fi

mkdir -p ~/cookbooks; cd ~/cookbooks
cat > soloistrc <<EOF
cookbook_paths:
- $PWD
recipes:
- pivotal_workstation::1password
- pivotal_workstation::ack
- pivotal_workstation::bash_completion
- pivotal_workstation::bettertouchtool
- pivotal_workstation::chrome
- pivotal_workstation::chrome_canary
- pivotal_workstation::create_var_chef_cache
- pivotal_workstation::defaults_fast_key_repeat_rate
- pivotal_workstation::default_editor
- pivotal_workstation::disable_front_row
- pivotal_workstation::dock_preferences
- pivotal_workstation::dropbox
- pivotal_workstation::enable_assistive_devices
- pivotal_workstation::firefox
- pivotal_workstation::function_keys
- pivotal_workstation::git
- pivotal_workstation::git_config_global_defaults
- pivotal_workstation::global_environment_variables
- pivotal_workstation::gnu-tar
- pivotal_workstation::google_drive
- pivotal_workstation::heroku_toolbelt
- pivotal_workstation::homebrew
- pivotal_workstation::imagemagick
- pivotal_workstation::increase_shared_memory
- pivotal_workstation::inputrc
- pivotal_workstation::java
- pivotal_workstation::jumpcut
- pivotal_workstation::keyboard_preferences
- pivotal_workstation::keycastr
- pivotal_workstation::libreoffice
- pivotal_workstation::locate_on
- pivotal_workstation::menubar_preferences
- pivotal_workstation::menumeters
- pivotal_workstation::mouse_locator
- pivotal_workstation::mysql
- pivotal_workstation::node_js
- pivotal_workstation::osx_disable_natural_scrolling
- pivotal_workstation::phantomjs
- pivotal_workstation::postgres
- pivotal_workstation::qt
- pivotal_workstation::rabbitmq
- pivotal_workstation::redis
- pivotal_workstation::rvm
- pivotal_workstation::screen_sharing_on
- pivotal_workstation::sequelpro
- pivotal_workstation::set_finder_show_user_home_in_sidebar
- pivotal_workstation::skype
- pivotal_workstation::source_code_pro_font
- pivotal_workstation::sshd_on
- pivotal_workstation::textmate
- pivotal_workstation::textmate2
- pivotal_workstation::textmate_bundles
- pivotal_workstation::textmate_preferences
- pivotal_workstation::tmux
- pivotal_workstation::unix_essentials
- pivotal_workstation::user_owns_usr_local
- pivotal_workstation::vim
- pivotal_workstation::virtualbox
- pivotal_workstation::vlc
- pivotal_workstation::watch
- pivotal_workstation::wget
- pivotal_workstation::workspace_directory
- pivotal_workstation::xquartz
EOF
if [[ -d pivotal_workstation ]]; then
  cd pivotal_workstation && git pull && cd ..
else
  git clone https://github.com/pivotal/pivotal_workstation.git
fi
if [[ -d dmg ]]; then
  cd dmg && git pull && cd ..
else
  git clone https://github.com/opscode-cookbooks/dmg.git
fi

if [[ "`sw_vers -productVersion`" == "10.7.5" ]]; then
  cd pivotal_workstation && git checkout last_lion_release && cd ..
fi

soloist
popd
