#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0)"
    echo "      Open todo.txt file in \$EDITOR for editing."
    echo ""
    exit
}

"${EDITOR:-vi}" "$TODO_FILE"
